# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' update_beta
#' 
#' update beta with Iteratively Reweighted Least Squares (IRLS)
#' inside function, do not need to export
#' @param y outcome matrix
#' @param X design matrix
#' @param n number of sample
#' @param p number of predictors
#' @param tol integer for tolerance value
#' @param iter_max integer to maximum iteration number 
#' @return beta a vector of estimated coefficients
#' @export
update_beta <- function(y, X, n, p, tol, iter_max) {
    .Call(`_LogisticReg_update_beta`, y, X, n, p, tol, iter_max)
}

